name: tweet_sample
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Data base  
  sqflite: ^2.0.3  

  # Localization
  intl: ^0.17.0

  # State manager
  mobx: ^2.0.7+4
  flutter_mobx: ^2.0.6+1

  # Service locator
  get_it: ^7.2.0

  # Path provider
  path_provider: ^2.0.11

  # Codegen
  mobx_codegen: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  # Runner
  build_runner: ^2.2.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
